version: '3'

services:

  jupyter-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - LOGLEVEL=DEBUG
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - SEDAS_USERNAME=${SEDAS_USERNAME}
      - SEDAS_PWD=${SEDAS_PWD}
    volumes:
      - ./:/opt/notebooks
    restart: always