
version: '3'

services:
  jupyter-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/opt/notebooks
    restart: always