
version: '3'

services:

  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - C:/Users/Tom.Jones/Documents/Data/redisdata:/data
      
  jupyter-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - LOGLEVEL=DEBUG
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - SEDAS_USERNAME=${SEDAS_USERNAME}
      - SEDAS_PWD=${SEDAS_PWD}
    volumes:
      - ./:/opt/notebooks
      - C:/Users/Tom.Jones/Documents/Data:/tmp/data
    restart: always